### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stadlereric** [vbarahona/Panos2Grafana#1]
can you update the instructions to include all the PAN MIB.my files. I needed all of them in order to poll the information you specified in your .conf file. Thanks for creating this!

PAN-COMMON-MIB.my
PAN-ENTITY-EXT-MIB.my
PAN-GLOBAL-REG-MIB.my
PAN-GLOBAL-TC-MIB.my
PAN-LC-MIB.my
PAN-PRODUCT-MIB.my
PAN-TRAPS.my

**Comment by vbarahona** [comment]
Hi,

very true. Already done.

Thanks for the feedback
