### ISSUE TITLE
Cannot find module (PAN-COMMON-MIB)

### ISSUE THREAD

**Issue by eduardocalfaia** [vbarahona/Panos2Grafana#2]
Hello dear,
I've followed your README to install your dashboard in our grafana but I have gotten the error below. May you help us?

Thanks

PAN-COMMON-MIB::panFlowIpfragFragErr: Unknown Object Identifier
May 24 22:21:00 STG-ZBX-FE telegraf[4622]: 2020-05-24T20:21:00Z E! [inputs.snmp] Error in plugin: initializing table pan_global_counters: initializing fiel
May 24 22:21:00 STG-ZBX-FE telegraf[4622]: Cannot find module (PAN-COMMON-MIB): At line 1 in (none)
May 24 22:21:00 STG-ZBX-FE telegraf[4622]: PAN-COMMON-MIB::panFlowIpfragFragErr: Unknown Object Identifier
May 24 22:22:00 STG-ZBX-FE telegraf[4622]: 2020-05-24T20:22:00Z E! [inputs.snmp] Error in plugin: initializing table pan_global_counters: initializing fiel
May 24 22:22:00 STG-ZBX-FE telegraf[4622]: Cannot find module (PAN-COMMON-MIB): At line 1 in (none)
May 24 22:22:00 STG-ZBX-FE telegraf[4622]: PAN-COMMON-MIB::panFlowIpfragFragErr: Unknown Object Identifier
May 24 22:23:00 STG-ZBX-FE telegraf[4622]: 2020-05-24T20:23:00Z E! [inputs.snmp] Error in plugin: initializing table pan_global_counters: initializing fiel
May 24 22:23:00 STG-ZBX-FE telegraf[4622]: Cannot find module (PAN-COMMON-MIB): At line 1 in (none)
May 24 22:23:00 STG-ZBX-FE telegraf[4622]: PAN-COMMON-MIB::panFlowIpfragFragErr: Unknown Object Identifier

**Comment by vbarahona** [comment]
Hi Eduardo,

I think that you don't have the PaloAlto MIBs definitions installed. Download them from https://github.com/vbarahona/Panos2Grafana/blob/master/pan-81-snmp-mib-modules.zip?raw=true and uncompress all the files in /etc/telegraf/telegraf.d/.snmp/mibs/ 

Regards.

**Comment by eduardocalfaia** [comment]
Hi @vbarahona,
Ok, thanks
