### ISSUE TITLE
CPS by Security Zone and by protocols and zones

### ISSUE THREAD

**Issue by eduardocalfaia** [vbarahona/Panos2Grafana#3]
Hello @vbarahona, how are you?
Fine I hope

Great dashboard. 

We have the 220, 3220, and 820 PA models, we have problems with the CPS by Security Zone and by protocols and zones graphics, do you have any idea what it would be? the Zones are known.

Thanks

**Comment by vbarahona** [comment]
Hi Eduardo.

Everything ok, it's nice that you like the dashboard  :-)

There is a bug in the CPS graphs. You can fix it by yourself. Enter in the CPS graphs and you will see that in the SELECT of that fields I'm using "FROM 4weeks". That's wrong. Change it to "default" and the data will appear.

Thanks for reporting. I will fix it soon in the repository and grafana.com.

Regards.

**Comment by eduardocalfaia** [comment]
Hi @vbarahona,
Thanks 
I've changed to default and work like a charm. 

Thanks
