### ISSUE TITLE
Unknown Object Identifier despite MIBs present in /etc/telegraf/telegraf.d/.snmp/mibs/

### ISSUE THREAD

**Issue by irom77** [vbarahona/Panos2Grafana#7]
Getting  Unknown Object Identifier despite directory _/etc/telegraf/telegraf.d/.snmp/mibs/_ including all MIBs

```
Cannot find module (PAN-COMMON-MIB): At line 0 in (none)
PAN-COMMON-MIB::panFlowIpfragFragErr: Unknown Object Identifier
command terminated with exit code 1
```

**Comment by vbarahona** [comment]
Hi,

I have just removed the needs of installing PAN-COMMON-MIB. Please review the new configuration and tell me if its solves you problem.

After that, re-import the dashboard from grafana.com as some changes has been done.

Regards.
